// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/advith-petstore-golang/pkg/models/shared"
	"net/http"
)

type ShowPetByIDPathParams struct {
	// The id of the pet to retrieve
	PetID string `pathParam:"style=simple,explode=false,name=petId"`
}

type ShowPetByIDRequest struct {
	PathParams ShowPetByIDPathParams
}

type ShowPetByIDResponse struct {
	ContentType string
	// unexpected error
	Error *shared.Error
	// Expected response to a valid request
	Pet         *shared.Pet
	StatusCode  int
	RawResponse *http.Response
}
